{{- $groups := .Values.groups | default (list) -}}
{{- $includeDefaultRules := true -}}
{{- if hasKey .Values.rules.network "includeDefaultRules" -}}
{{- $includeDefaultRules = .Values.rules.network.includeDefaultRules -}}
{{- end -}}
{{- $defaultRules := list -}}
{{- if $includeDefaultRules -}}
{{- $defaultRules = (.Values.rules.network.defaultRules | default (list)) -}}
{{- end -}}
{{- $items := concat $groups (concat (.Values.rules.network.rules | default (list)) $defaultRules) -}}
{{- if $items }}
apiVersion: v1
items:
{{ toYaml $items | indent 0 }}
kind: List
metadata: null
{{- end }}
